# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Docker Images

  jobs:  
  - job: Build amd64 image
    displayName: Build amd64 image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.amd64'
        tags: |
          $(tag)